on:
  release:
    types: [created]

jobs:
  release:
    name: release binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ['linux', 'windows']
        goarch: ['amd64']
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: mangadex-dowloader
